function text=addComments(text,s)
comment={...
    'space','Name of space';...
    'pMengs','p-value wheather the predicted correlation differs from the correlation to another variable using Meng''s test';...
    'rVersusN','Correlation (r) and p-values (p) as a function of number of predicitve words (N), divided into five categoris of N';...
    'AUC','Area Under the Curve (AUC), performance measure based Receiver operating characteristic (ROC) ';...
    'Lambda','Lambda parameters that is optimized in Lasso regression';...
    'noneDefaultParameters','List of non-default parameters';...
    'binaryPrecision','Precision for binary data';...
    'binaryHit','Hits';...
    'binaryCorrectRejection','Correct rejections';...
    'binaryFA','False alarm rate';...
    'binaryMisses','Misses';...
    'binaryThreshold','Threshold for categorizing the predicted value as 1, otherwise 0';...
    'binaryRecall','Recall for binary data';...
    'binaryNHigh','Number of data points above the mean value';...
    'clusterP','Probability that clusters of words differ in the number of occurrences of words in each class, uncorrected for multiple comparisons';...
    'clusterQ','Q-values in chi2-tests related to the probability that clusters of words differ in the number of occurrences of words in each class, uncorrected for multiple comparisons';...
    'LIWC','Linguist Inquiry Word Count (LIWC) method as introduced by Pennebaker';...
    'p','The probability of obtaining results as extreme or more extreme given that the null hypothesis is true';...
    'pOutlinersRemoved','The probability of obtaining results as extreme or more extreme given that the null hypothesis is true, following removal of outliners (i.e. outside of training data)';...
    'pcorrected','Probability that the null-hypothesis is true corrected for multiple comparisons by multiplying p with N';...
    'pN','Probability that the number of words per text is equal for dataset 1 and 2';...
    'q','Q-value from the Chi-squared test';...
    'df','degrees of freedom';...
    'r','Pearson correlation coefficient between predicted and empirical values';...
    'rStd','Standard deviation of Pearson correlation coefficient between predicted and empirical values';...
    'rOutlinersRemoved','Pearson correlation coefficient between predicted and empirical values while removing outliners (i.e. outside of the trained variable)';...
    'n','Number of data points';...
    'nWordsFound','Total number of words in the texts that also are present in the semantic representation';...
    'nWords','Total number of words in the texts';...
    'modelName','Identifier of the trained model';...
    'modelNumber','Serial order of the training';...    
    'c','constant term in the regression';...
    'Nremoved','Number of removed or missing data points';...
    'ndim','Mean number of dimensions used in the prediction';...
    'nStddim','Standard deviation of the number of predictions used in the prediction';...
    'rGroup','Pearson correlation coefficient between predicted and empirical values, for groupEd data (df=Ngroups)';...
    'pGroup','Probability that the null-hypothesis is true between predicted and empirical values, for groupEd data (df=Ngroups)';...
    'NGroups','Number of groups used during cross-validation';...
    'beta','Beta cofficient in the regression';...
    'data','Numerical data to predict';...
    'pred','Predicted values, using a cross-validation based on Ngroups-leave out procedure';...
    'textPredHigh','Data sorted by predicted values from high to low';...
    'textPredLow','Data sorted by predicted values from low to high';...
    'textDataHigh','Data sorted by empirical values from high to low';...
    'textDataLow','Data sorted by empirical values from low to high';...
    'significantDimensions','Dimensions used in the prediction, sorted high-to-low by how well they predict the empirical values';...
    'pcovariates','The probability of obtaining results as extreme or more extreme given that the null hypothesis is true, after controlling for covariates';...
    't','t-statistics';...
    'z','Mean value divided by standard deviation of the mean';...
    'cohensD','Cohen''s d, i.e. value minus mean value divided by standard deviation of the mean';...
    'effectSize','Effect size, d''';...
    'm1','Mean value of set 1';...
    'mean1','Mean value of set 1';...
    'm2','Mean value of set 2';...
    'mmean2','Mean value of set 2';...
    's1','Standard deviation of set 1';...
    'sd1','Standard deviation of set 1';...
    's2','Standard deviation of set 2';...
    'sd2','Standard deviation of set 2';...    
    'MeanSemanticScaleSet1','Mean value of the Semantic Scale on set 1 (i.e., based on the cosines of the angle between the semantic representations in set 1 and the semantic comparison representation)';...
    'MeanSemanticScaleSet2','Mean value of the Semantic Scale on set 2 (i.e., based on the cosines of the angle between the semantic representations in set 2 and the semantic comparison representation)';...
    'StdSemanticScaleSet1','Standard deviation of the Semantic Scale on set 1 (i.e., based on the cosines of the angle between the semantic representations in set 1 and the semantic comparison representation)';...
    'StdSemanticScaleSet2','Standard deviation of the Semantic Scale on set 2 (i.e., based on the cosines of the angle between the semantic representations in set 2 and the semantic comparison representation)';...    
    'n1','Number of data points in set 1';...
    'n2','Number of data points in set 2';...
    'n1text','Number of texts in set 1';...
    'n2text','Number of texts in set 2';...
    'correct','Percentage correct classifications';...
    'similarity','Cosines of the angel between set 1 and 2';...
    'SemanticSimilarity','Cosines of the angel between set 1 and 2';...
    'pKS1','Probability that set 1 distribution differs from a normal distribution';...
    'pKS2','Probability that set 2 distribution differs from a normal distribution';...
    'x1','Values on the semantic scale for set 1';...
    'x2','Values on the semantic scale for set 2';...
    'assocites','Semantic associates';...
    'keywords1','Words where the frequency of occurrence are significantly higher in set 1 compared to set 2, following corrections for multiple-comparisons';...
    'keywords2','Words where the frequency of occurrence are significantly higher in set 2 compared to set 1, following corrections for multiple-comparisons';...
    'keywordsCorr1','Words with a frequency that is positively correlated to a variable';...
    'keywordsCorr2','Words with a frequency that is negatively correlated to a variable';...
    'relevantKeywords1','Words where the frequency of occurrence are significantly higher in set 1 compared to set 2,and that are among the 100 most overrepresented words relative to a norm in the languge, following corrections for multiple-comparisons';...
    'relevantKeywords2','Words where the frequency of occurrence are significantly higher in set 2 compared to set 1,and that are among the 100 most overrepresented words relative to a norm in the languge, following corrections for multiple-comparisons';...
    'keywordsWCstring','Words where the frequency of occurrence are significantly higher in set 2 compared to set 1,divided into wordclasses';...    
    'Nunique','Number of unique words in set 1 and 2';...
    'word','List of words ordered by decreasing frequency';...
    'f1','Frequency counts of words in set 1';...
    'f2','Frequency counts of words in set 2';...
    'keywordsNorm1','Words where the frequency of occurrence are significantly higher in set 1 compared to a frequency norm of the language, corrected for multiple comparisons';...
    'semanticAssocates1','Keywords ordered by semantic similarity to set 1 compared set 2, ordered by the semantic similarity to set 1 versus set 2. The number of words printed is a user-speficied parameter';...
    'semanticAssocates2','Keywords ordered by semantic similarity to set 2 compared set 1, ordered by the semantic similarity to set 2 versus set 1. The number of words printed is a user-speficied parameter';...
    'x','Semantic representation';...
    'associates','Words ordered by decreasing similarity to the semantic representation';...
    'keywordsCluster1','Cluster of words (as defined by clusterDefinition), where the frequency of occurrence are significantly higher in set 1 compared to set 2, following corrections for multiple-comparisons';...
    'keywordsCluster2','Cluster of words (as defined by clusterDefinition), where the frequency of occurrence are significantly higher set 2 compared to set 1, following corrections for multiple-comparisons';...
    'clusterDefinition','Defines N clusters, by semantic associates';...
    'trainDataStat','Statistic of training data set: mean std min max skewness';...
    'predDataStat','Statistic of predicted values during training: mean std min max skewness';...
    };
N=size(comment);
for i=1:N(1)
    j1=findstr([char(13) lower(text)],[char(13) lower(comment{i,1}) '=']);
    if j1>0
        j2=findstr([text(j1:end)],[char(13)]);
        if length(j2)>1 j2=j2(1);end
        if strcmpi(text(j1+length(comment{i,1})+1:j1+j2(1)-3),'NaN') 
            text=[text(1:j1-2) text(j1+j2-1:end) ];
        else
            text=[text(1:j1+j2-2) char(9) '%' comment{i,2} text(j1+j2-1:end) ];
        end
    end
end
for i=1:10
    text=regexprep(text,['comment' num2str(i) '='],[char(13) '%']);
end
if nargin>=2 %Remove very long texts (i.e. lines longer than s.par.maxPrintedCharacters)!
    text(end+1)=char(13);
    if not(s.par.excelServer) %Do not remove long texts data in excelSever!
        istart=1;
        i=findstr(text,char(13));
        for j=1:length(i)
            if i(j)-istart>s.par.maxPrintedCharacters
                text=[text(1:istart+s.par.maxPrintedCharacters) ' %DATA TRUNCATED HERE!!!'  text(i(j):end) ];
            end
            i=findstr(text,char(13));
            istart=i(j);
        end
    end
end
text=regexprep(text,char(13),char(10));
        